import pyodbc
from config import connection_string
from datetime import datetime

def insert_data(auto_generated_case_id, master_id, case_id, reported_time, sector, field_c, field_d, field_e, field_f, field_g, field_h, field_i):
    try:
        conn = pyodbc.connect(connection_string)
        cursor = conn.cursor()

        insert_query = """
            INSERT INTO GlobalCaseDetails (AutoGeneratedCaseId, MasterId, CaseId, ReportedTime, Sector, FieldC, FieldD, FieldE, FieldF, FieldG, FieldH, FieldI, AddedDate, Status)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """
        
        # Prepare parameters, assuming AddedDate is the current time and Status is set to 'New' by default
        params = (
            auto_generated_case_id, master_id, case_id, reported_time, sector,
            field_c, field_d, field_e, field_f, field_g, field_h, field_i,
            datetime.now(), 'started'  # AddedDate and default Status
        )
        
        cursor.execute(insert_query, params)
        conn.commit()

        cursor.close()
        conn.close()
        return {"status": "success", "message": "Data inserted successfully."}
    except Exception as e:
        return {"status": "error", "message": str(e)}