CREATE PROCEDURE InsertGlobalCaseDetails
    @AutoGeneratedCaseId NVARCHAR(50),
    @MasterId NVARCHAR(50),
    @CaseId NVARCHAR(50),
    @ReportedTime DATETIME,
    @Sector NVARCHAR(50),
    @FieldC NVARCHAR(50),
    @FieldD NVARCHAR(50),
    @FieldE NVARCHAR(50),
    @FieldF NVARCHAR(50),
    @FieldG NVARCHAR(50),
    @FieldH NVARCHAR(50),
    @FieldI NVARCHAR(50),
    @AddedDate DATETIME,
    @Status NVARCHAR(20),
    @CompletedDate DATETIME
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO GlobalCaseDetails (
        AutoGeneratedCaseId, MasterId, CaseId, ReportedTime, Sector,
        FieldC, FieldD, FieldE, FieldF, FieldG, FieldH, FieldI,
        AddedDate, Status, CompletedDate
    )
    VALUES (
        @AutoGeneratedCaseId, @MasterId, @CaseId, @ReportedTime, @Sector,
        @FieldC, @FieldD, @FieldE, @FieldF, @FieldG, @FieldH, @FieldI,
        @AddedDate, @Status, @CompletedDate
    );

    -- Return the new Id of the inserted row
    SELECT SCOPE_IDENTITY() AS NewId;
END;
